!        generated by tapenade     (inria, ecuador team)
!  tapenade 3.16 (develop) -  2 sep 2026 09:00
!
! this module contains the source terms for two variants of the
! spalart-allmaras turbulence model that are not part of the
! "standard" sa implementation in sa.f90:
!
!   1. the edwards-chandra modification (sa-noft2-edwards), selected with
!      turbulencemodel = "sa-edwards":
!
!        edwards, j. r. and chandra, s., "comparison of eddy
!        viscosity-transport turbulence models for three-dimensional,
!        shock-separated flowfields," aiaa paper 94-2275, 1994,
!        https://doi.org/10.2514/6.1994-2275; also aiaa journal,
!        vol. 34, no. 4, 1996, pp. 756-763, https://doi.org/10.2514/3.13137.
!
!      the model is identical to standard sa except that ft2 is ignored
!      and
!
!        stilde = sqrt(s) * (1/chi + fv1)
!        r      = tanh(nutilde / (stilde kappa^2 d^2)) / tanh(1)
!        s      = (du_i/dx_j + du_j/dx_i) du_i/dx_j - 2/3 (du_k/dx_k)^2
!
!      i.e. the strain rate, not the vorticity, drives production. note
!      that stilde * nutilde = sqrt(s) * (nu + nutilde * fv1), which is how
!      the terms are evaluated here to avoid the 1/chi singularity at walls.
!
!   2. the mixing-layer compressibility correction (sa-comp), selected with
!      usecompressibilitysa = true, which can be combined with either
!      "sa" or "sa-edwards":
!
!        spalart, p. r., "trends in turbulence treatments," aiaa paper
!        2000-2306, 2000, https://doi.org/10.2514/6.2000-2306.
!
!      the following term is added to the right hand side of the
!      (non-conservative) nutilde equation,
!
!        -c5 * nutilde^2 / a^2 * (du_i/dx_j) (du_i/dx_j),   c5 = 3.5,
!
!      where a is the local speed of sound.
!
! the routines follow the conventions of sasource in sa.f90: the source
! is stored in scratch(:,:,:,idvt) and -dsource/dnutilde is stored in qq
! for the ddadi solver. they are differentiated with tapenade (see
! adjoint/makefile_tapenade).
module sacorrections_d
  use constants
  implicit none

contains
!  differentiation of saedwardssource in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: *scratch
!   with respect to varying inputs: *w *rlv *vol *d2wall *si *sj
!                *sk
!   rw status of diff variables: *w:in *rlv:in *scratch:out *vol:in
!                *d2wall:in *si:in *sj:in *sk:in
!   plus diff mem management of: w:in rlv:in scratch:in vol:in
!                d2wall:in si:in sj:in sk:in
  subroutine saedwardssource_d()
!
!  source terms of the edwards-chandra sa model.
!  determine the source term and its derivative w.r.t. nutilde
!  for all internal cells of the block.
!  remember that the sa field variable nutilde = w(i,j,k,itu1)
    use blockpointers
    use constants
    use paramturb
    use inputdiscretization, only : approxsa
    implicit none
! local parameters
    real(kind=realtype), parameter :: f23=two*third
    real(kind=realtype), parameter :: xminn=1.e-10_realtype
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: cv13, kar2inv, cw36, tanhoneinv
    real(kind=realtype) :: fv1, nufv, ss, nu, dist2inv, chi, chi2, chi3
    real(kind=realtype) :: fv1d, nufvd, ssd, nud, dist2invd, chid, chi2d&
&   , chi3d
    real(kind=realtype) :: xx, tanhx, rr, gg, gg6, termfw, fwsa
    real(kind=realtype) :: xxd, tanhxd, rrd, ggd, gg6d, termfwd, fwsad
    real(kind=realtype) :: prod, dest
    real(kind=realtype) :: prodd, destd
    real(kind=realtype) :: dfv1, dnufv, dxx, drr, dgg, dfw
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: uuxd, uuyd, uuzd, vvxd, vvyd, vvzd, wwxd, &
&   wwyd, wwzd
    real(kind=realtype) :: div2, fact, sxx, syy, szz, sxy, sxz, syz
    real(kind=realtype) :: div2d, factd, sxxd, syyd, szzd, sxyd, sxzd, &
&   syzd
    real(kind=realtype) :: strainmag2, strainprod
    real(kind=realtype) :: strainmag2d, strainprodd
    intrinsic tanh
    intrinsic max
    intrinsic sqrt
    real(kind=realtype) :: max1
    real(kind=realtype) :: max1d
    real(kind=realtype) :: temp
    real(kind=realtype) :: temp0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: temp2
    real(kind=realtype) :: temp3
    real(kind=realtype) :: temp4
    real(kind=realtype) :: temp5
    real(kind=realtype) :: temp6
    real(kind=realtype) :: temp7
    real(kind=realtype) :: temp8
    real(kind=realtype) :: temp9
    real(kind=realtype) :: temp10
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
    tanhoneinv = one/tanh(one)
    if (associated(scratchd)) scratchd = 0.0_8
    do k=2,kl
      do j=2,jl
        do i=2,il
! compute the velocity gradients in the cell center,
! scaled by 2*vol. see sasource in sa.f90.
          temp = si(i, j, k, 1)
          temp0 = w(i+1, j, k, ivx)
          temp1 = si(i-1, j, k, 1)
          temp2 = w(i-1, j, k, ivx)
          temp3 = sj(i, j, k, 1)
          temp4 = w(i, j+1, k, ivx)
          temp5 = sk(i, j, k, 1)
          temp6 = w(i, j, k+1, ivx)
          temp7 = sj(i, j-1, k, 1)
          temp8 = w(i, j-1, k, ivx)
          temp9 = sk(i, j, k-1, 1)
          temp10 = w(i, j, k-1, ivx)
          uuxd = temp*wd(i+1, j, k, ivx) + temp0*sid(i, j, k, 1) - temp1&
&           *wd(i-1, j, k, ivx) - temp2*sid(i-1, j, k, 1) + temp3*wd(i, &
&           j+1, k, ivx) + temp4*sjd(i, j, k, 1) + temp5*wd(i, j, k+1, &
&           ivx) + temp6*skd(i, j, k, 1) - temp7*wd(i, j-1, k, ivx) - &
&           temp8*sjd(i, j-1, k, 1) - temp9*wd(i, j, k-1, ivx) - temp10*&
&           skd(i, j, k-1, 1)
          uux = temp0*temp - temp2*temp1 + temp4*temp3 + temp6*temp5 - &
&           temp8*temp7 - temp10*temp9
          temp10 = si(i, j, k, 2)
          temp9 = w(i+1, j, k, ivx)
          temp8 = si(i-1, j, k, 2)
          temp7 = w(i-1, j, k, ivx)
          temp6 = sj(i, j, k, 2)
          temp5 = w(i, j+1, k, ivx)
          temp4 = sk(i, j, k, 2)
          temp3 = w(i, j, k+1, ivx)
          temp2 = sj(i, j-1, k, 2)
          temp1 = w(i, j-1, k, ivx)
          temp0 = sk(i, j, k-1, 2)
          temp = w(i, j, k-1, ivx)
          uuyd = temp10*wd(i+1, j, k, ivx) + temp9*sid(i, j, k, 2) - &
&           temp8*wd(i-1, j, k, ivx) - temp7*sid(i-1, j, k, 2) + temp6*&
&           wd(i, j+1, k, ivx) + temp5*sjd(i, j, k, 2) + temp4*wd(i, j, &
&           k+1, ivx) + temp3*skd(i, j, k, 2) - temp2*wd(i, j-1, k, ivx)&
&           - temp1*sjd(i, j-1, k, 2) - temp0*wd(i, j, k-1, ivx) - temp*&
&           skd(i, j, k-1, 2)
          uuy = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 3)
          temp9 = w(i+1, j, k, ivx)
          temp8 = si(i-1, j, k, 3)
          temp7 = w(i-1, j, k, ivx)
          temp6 = sj(i, j, k, 3)
          temp5 = w(i, j+1, k, ivx)
          temp4 = sk(i, j, k, 3)
          temp3 = w(i, j, k+1, ivx)
          temp2 = sj(i, j-1, k, 3)
          temp1 = w(i, j-1, k, ivx)
          temp0 = sk(i, j, k-1, 3)
          temp = w(i, j, k-1, ivx)
          uuzd = temp10*wd(i+1, j, k, ivx) + temp9*sid(i, j, k, 3) - &
&           temp8*wd(i-1, j, k, ivx) - temp7*sid(i-1, j, k, 3) + temp6*&
&           wd(i, j+1, k, ivx) + temp5*sjd(i, j, k, 3) + temp4*wd(i, j, &
&           k+1, ivx) + temp3*skd(i, j, k, 3) - temp2*wd(i, j-1, k, ivx)&
&           - temp1*sjd(i, j-1, k, 3) - temp0*wd(i, j, k-1, ivx) - temp*&
&           skd(i, j, k-1, 3)
          uuz = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 1)
          temp9 = w(i+1, j, k, ivy)
          temp8 = si(i-1, j, k, 1)
          temp7 = w(i-1, j, k, ivy)
          temp6 = sj(i, j, k, 1)
          temp5 = w(i, j+1, k, ivy)
          temp4 = sk(i, j, k, 1)
          temp3 = w(i, j, k+1, ivy)
          temp2 = sj(i, j-1, k, 1)
          temp1 = w(i, j-1, k, ivy)
          temp0 = sk(i, j, k-1, 1)
          temp = w(i, j, k-1, ivy)
          vvxd = temp10*wd(i+1, j, k, ivy) + temp9*sid(i, j, k, 1) - &
&           temp8*wd(i-1, j, k, ivy) - temp7*sid(i-1, j, k, 1) + temp6*&
&           wd(i, j+1, k, ivy) + temp5*sjd(i, j, k, 1) + temp4*wd(i, j, &
&           k+1, ivy) + temp3*skd(i, j, k, 1) - temp2*wd(i, j-1, k, ivy)&
&           - temp1*sjd(i, j-1, k, 1) - temp0*wd(i, j, k-1, ivy) - temp*&
&           skd(i, j, k-1, 1)
          vvx = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 2)
          temp9 = w(i+1, j, k, ivy)
          temp8 = si(i-1, j, k, 2)
          temp7 = w(i-1, j, k, ivy)
          temp6 = sj(i, j, k, 2)
          temp5 = w(i, j+1, k, ivy)
          temp4 = sk(i, j, k, 2)
          temp3 = w(i, j, k+1, ivy)
          temp2 = sj(i, j-1, k, 2)
          temp1 = w(i, j-1, k, ivy)
          temp0 = sk(i, j, k-1, 2)
          temp = w(i, j, k-1, ivy)
          vvyd = temp10*wd(i+1, j, k, ivy) + temp9*sid(i, j, k, 2) - &
&           temp8*wd(i-1, j, k, ivy) - temp7*sid(i-1, j, k, 2) + temp6*&
&           wd(i, j+1, k, ivy) + temp5*sjd(i, j, k, 2) + temp4*wd(i, j, &
&           k+1, ivy) + temp3*skd(i, j, k, 2) - temp2*wd(i, j-1, k, ivy)&
&           - temp1*sjd(i, j-1, k, 2) - temp0*wd(i, j, k-1, ivy) - temp*&
&           skd(i, j, k-1, 2)
          vvy = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 3)
          temp9 = w(i+1, j, k, ivy)
          temp8 = si(i-1, j, k, 3)
          temp7 = w(i-1, j, k, ivy)
          temp6 = sj(i, j, k, 3)
          temp5 = w(i, j+1, k, ivy)
          temp4 = sk(i, j, k, 3)
          temp3 = w(i, j, k+1, ivy)
          temp2 = sj(i, j-1, k, 3)
          temp1 = w(i, j-1, k, ivy)
          temp0 = sk(i, j, k-1, 3)
          temp = w(i, j, k-1, ivy)
          vvzd = temp10*wd(i+1, j, k, ivy) + temp9*sid(i, j, k, 3) - &
&           temp8*wd(i-1, j, k, ivy) - temp7*sid(i-1, j, k, 3) + temp6*&
&           wd(i, j+1, k, ivy) + temp5*sjd(i, j, k, 3) + temp4*wd(i, j, &
&           k+1, ivy) + temp3*skd(i, j, k, 3) - temp2*wd(i, j-1, k, ivy)&
&           - temp1*sjd(i, j-1, k, 3) - temp0*wd(i, j, k-1, ivy) - temp*&
&           skd(i, j, k-1, 3)
          vvz = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 1)
          temp9 = w(i+1, j, k, ivz)
          temp8 = si(i-1, j, k, 1)
          temp7 = w(i-1, j, k, ivz)
          temp6 = sj(i, j, k, 1)
          temp5 = w(i, j+1, k, ivz)
          temp4 = sk(i, j, k, 1)
          temp3 = w(i, j, k+1, ivz)
          temp2 = sj(i, j-1, k, 1)
          temp1 = w(i, j-1, k, ivz)
          temp0 = sk(i, j, k-1, 1)
          temp = w(i, j, k-1, ivz)
          wwxd = temp10*wd(i+1, j, k, ivz) + temp9*sid(i, j, k, 1) - &
&           temp8*wd(i-1, j, k, ivz) - temp7*sid(i-1, j, k, 1) + temp6*&
&           wd(i, j+1, k, ivz) + temp5*sjd(i, j, k, 1) + temp4*wd(i, j, &
&           k+1, ivz) + temp3*skd(i, j, k, 1) - temp2*wd(i, j-1, k, ivz)&
&           - temp1*sjd(i, j-1, k, 1) - temp0*wd(i, j, k-1, ivz) - temp*&
&           skd(i, j, k-1, 1)
          wwx = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 2)
          temp9 = w(i+1, j, k, ivz)
          temp8 = si(i-1, j, k, 2)
          temp7 = w(i-1, j, k, ivz)
          temp6 = sj(i, j, k, 2)
          temp5 = w(i, j+1, k, ivz)
          temp4 = sk(i, j, k, 2)
          temp3 = w(i, j, k+1, ivz)
          temp2 = sj(i, j-1, k, 2)
          temp1 = w(i, j-1, k, ivz)
          temp0 = sk(i, j, k-1, 2)
          temp = w(i, j, k-1, ivz)
          wwyd = temp10*wd(i+1, j, k, ivz) + temp9*sid(i, j, k, 2) - &
&           temp8*wd(i-1, j, k, ivz) - temp7*sid(i-1, j, k, 2) + temp6*&
&           wd(i, j+1, k, ivz) + temp5*sjd(i, j, k, 2) + temp4*wd(i, j, &
&           k+1, ivz) + temp3*skd(i, j, k, 2) - temp2*wd(i, j-1, k, ivz)&
&           - temp1*sjd(i, j-1, k, 2) - temp0*wd(i, j, k-1, ivz) - temp*&
&           skd(i, j, k-1, 2)
          wwy = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 3)
          temp9 = w(i+1, j, k, ivz)
          temp8 = si(i-1, j, k, 3)
          temp7 = w(i-1, j, k, ivz)
          temp6 = sj(i, j, k, 3)
          temp5 = w(i, j+1, k, ivz)
          temp4 = sk(i, j, k, 3)
          temp3 = w(i, j, k+1, ivz)
          temp2 = sj(i, j-1, k, 3)
          temp1 = w(i, j-1, k, ivz)
          temp0 = sk(i, j, k-1, 3)
          temp = w(i, j, k-1, ivz)
          wwzd = temp10*wd(i+1, j, k, ivz) + temp9*sid(i, j, k, 3) - &
&           temp8*wd(i-1, j, k, ivz) - temp7*sid(i-1, j, k, 3) + temp6*&
&           wd(i, j+1, k, ivz) + temp5*sjd(i, j, k, 3) + temp4*wd(i, j, &
&           k+1, ivz) + temp3*skd(i, j, k, 3) - temp2*wd(i, j-1, k, ivz)&
&           - temp1*sjd(i, j-1, k, 3) - temp0*wd(i, j, k-1, ivz) - temp*&
&           skd(i, j, k-1, 3)
          wwz = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
! strain rate tensor; the factor 1/(4*vol) accounts for
! the 2*vol scaling of the gradients.
          temp10 = fourth/vol(i, j, k)
          factd = -(temp10*vold(i, j, k)/vol(i, j, k))
          fact = temp10
          sxxd = two*(uux*factd+fact*uuxd)
          sxx = two*fact*uux
          syyd = two*(vvy*factd+fact*vvyd)
          syy = two*fact*vvy
          szzd = two*(wwz*factd+fact*wwzd)
          szz = two*fact*wwz
          sxyd = (uuy+vvx)*factd + fact*(uuyd+vvxd)
          sxy = fact*(uuy+vvx)
          sxzd = (uuz+wwx)*factd + fact*(uuzd+wwxd)
          sxz = fact*(uuz+wwx)
          syzd = (vvz+wwy)*factd + fact*(vvzd+wwyd)
          syz = fact*(vvz+wwy)
          div2d = f23*2*(sxx+syy+szz)*(sxxd+syyd+szzd)
          div2 = f23*(sxx+syy+szz)**2
          strainmag2d = two*(2*sxy*sxyd+2*sxz*sxzd+2*syz*syzd) + 2*sxx*&
&           sxxd + 2*syy*syyd + 2*szz*szzd
          strainmag2 = two*(sxy**2+sxz**2+syz**2) + sxx**2 + syy**2 + &
&           szz**2
! s = 2 s_ij s_ij - 2/3 (div u)^2. edwards uses sqrt(s).
! limit it from below (like sst in sa.f90), which also
! keeps the derivative of the square root finite.
          strainprodd = two*strainmag2d - div2d
          strainprod = two*strainmag2 - div2
          if (strainprod .lt. xminn**2) then
            max1 = xminn**2
            max1d = 0.0_8
          else
            max1d = strainprodd
            max1 = strainprod
          end if
          temp10 = sqrt(max1)
          if (max1 .eq. 0.0_8) then
            ssd = 0.0_8
          else
            ssd = max1d/(2.0*temp10)
          end if
          ss = temp10
! laminar kinematic viscosity, inverse wall distance
! squared, chi and fv1.
          temp10 = w(i, j, k, irho)
          temp9 = rlv(i, j, k)/temp10
          nud = (rlvd(i, j, k)-temp9*wd(i, j, k, irho))/temp10
          nu = temp9
          temp10 = one/(d2wall(i, j, k)*d2wall(i, j, k))
          dist2invd = -(temp10*2*d2walld(i, j, k)/d2wall(i, j, k))
          dist2inv = temp10
          temp10 = w(i, j, k, itu1)/nu
          chid = (wd(i, j, k, itu1)-temp10*nud)/nu
          chi = temp10
          chi2d = 2*chi*chid
          chi2 = chi*chi
          chi3d = chi2*chid + chi*chi2d
          chi3 = chi*chi2
          temp10 = chi3/(cv13+chi3)
          fv1d = (1.0-temp10)*chi3d/(cv13+chi3)
          fv1 = temp10
! nufv = nu + nutilde*fv1, such that
! stilde * nutilde = ss * nufv.
          temp10 = w(i, j, k, itu1)
          nufvd = nud + fv1*wd(i, j, k, itu1) + temp10*fv1d
          nufv = nu + temp10*fv1
          if (nufv .lt. xminn*nu) then
            nufvd = xminn*nud
            nufv = xminn*nu
          else
            nufv = nufv
          end if
! r = tanh(nutilde / (stilde kappa^2 d^2)) / tanh(1)
!   = tanh(nutilde^2 / (ss nufv kappa^2 d^2)) / tanh(1).
! no cut-off is needed since r <= 1/tanh(1).
          temp10 = dist2inv/(ss*nufv)
          temp9 = w(i, j, k, itu1)
          xxd = kar2inv*(temp10*2*temp9*wd(i, j, k, itu1)+temp9**2*(&
&           dist2invd-temp10*(nufv*ssd+ss*nufvd))/(ss*nufv))
          xx = kar2inv*(temp9*temp9*temp10)
          tanhxd = (1.0-tanh(xx)**2)*xxd
          tanhx = tanh(xx)
          rrd = tanhoneinv*tanhxd
          rr = tanhx*tanhoneinv
          ggd = (rsacw2*(6*rr**5-1.0)+1.0)*rrd
          gg = rr + rsacw2*(rr**6-rr)
          gg6d = 6*gg**5*ggd
          gg6 = gg**6
          temp10 = (one+cw36)/(cw36+gg6)
          if (temp10 .le. 0.0_8 .and. (sixth .eq. 0.0_8 .or. sixth .ne. &
&             int(sixth))) then
            termfwd = 0.0_8
          else
            termfwd = -(sixth*temp10**(sixth-1)*temp10*gg6d/(cw36+gg6))
          end if
          termfw = temp10**sixth
          fwsad = termfw*ggd + gg*termfwd
          fwsa = gg*termfw
! production cb1*stilde*nutilde and destruction.
          if (approxsa) then
            prod = zero
            prodd = 0.0_8
          else
            prodd = rsacb1*(nufv*ssd+ss*nufvd)
            prod = rsacb1*ss*nufv
          end if
          temp10 = w(i, j, k, itu1)
          destd = rsacw1*(temp10**2*(dist2inv*fwsad+fwsa*dist2invd)+fwsa&
&           *dist2inv*2*temp10*wd(i, j, k, itu1))
          dest = rsacw1*(fwsa*dist2inv*(temp10*temp10))
          scratchd(i, j, k, idvt) = prodd - destd
          scratch(i, j, k, idvt) = prod - dest
        end do
      end do
    end do
  end subroutine saedwardssource_d

  subroutine saedwardssource()
!
!  source terms of the edwards-chandra sa model.
!  determine the source term and its derivative w.r.t. nutilde
!  for all internal cells of the block.
!  remember that the sa field variable nutilde = w(i,j,k,itu1)
    use blockpointers
    use constants
    use paramturb
    use inputdiscretization, only : approxsa
    implicit none
! local parameters
    real(kind=realtype), parameter :: f23=two*third
    real(kind=realtype), parameter :: xminn=1.e-10_realtype
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: cv13, kar2inv, cw36, tanhoneinv
    real(kind=realtype) :: fv1, nufv, ss, nu, dist2inv, chi, chi2, chi3
    real(kind=realtype) :: xx, tanhx, rr, gg, gg6, termfw, fwsa
    real(kind=realtype) :: prod, dest
    real(kind=realtype) :: dfv1, dnufv, dxx, drr, dgg, dfw
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: div2, fact, sxx, syy, szz, sxy, sxz, syz
    real(kind=realtype) :: strainmag2, strainprod
    intrinsic tanh
    intrinsic max
    intrinsic sqrt
    real(kind=realtype) :: max1
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
    tanhoneinv = one/tanh(one)
    do k=2,kl
      do j=2,jl
        do i=2,il
! compute the velocity gradients in the cell center,
! scaled by 2*vol. see sasource in sa.f90.
          uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(&
&           i-1, j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1&
&           , k, ivx)*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1&
&           ) - w(i, j, k-1, ivx)*sk(i, j, k-1, 1)
          uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(&
&           i-1, j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1&
&           , k, ivx)*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2&
&           ) - w(i, j, k-1, ivx)*sk(i, j, k-1, 2)
          uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(&
&           i-1, j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1&
&           , k, ivx)*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3&
&           ) - w(i, j, k-1, ivx)*sk(i, j, k-1, 3)
          vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(&
&           i-1, j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1&
&           , k, ivy)*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1&
&           ) - w(i, j, k-1, ivy)*sk(i, j, k-1, 1)
          vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(&
&           i-1, j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1&
&           , k, ivy)*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2&
&           ) - w(i, j, k-1, ivy)*sk(i, j, k-1, 2)
          vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(&
&           i-1, j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1&
&           , k, ivy)*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3&
&           ) - w(i, j, k-1, ivy)*sk(i, j, k-1, 3)
          wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(&
&           i-1, j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1&
&           , k, ivz)*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1&
&           ) - w(i, j, k-1, ivz)*sk(i, j, k-1, 1)
          wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(&
&           i-1, j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1&
&           , k, ivz)*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2&
&           ) - w(i, j, k-1, ivz)*sk(i, j, k-1, 2)
          wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(&
&           i-1, j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1&
&           , k, ivz)*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3&
&           ) - w(i, j, k-1, ivz)*sk(i, j, k-1, 3)
! strain rate tensor; the factor 1/(4*vol) accounts for
! the 2*vol scaling of the gradients.
          fact = fourth/vol(i, j, k)
          sxx = two*fact*uux
          syy = two*fact*vvy
          szz = two*fact*wwz
          sxy = fact*(uuy+vvx)
          sxz = fact*(uuz+wwx)
          syz = fact*(vvz+wwy)
          div2 = f23*(sxx+syy+szz)**2
          strainmag2 = two*(sxy**2+sxz**2+syz**2) + sxx**2 + syy**2 + &
&           szz**2
! s = 2 s_ij s_ij - 2/3 (div u)^2. edwards uses sqrt(s).
! limit it from below (like sst in sa.f90), which also
! keeps the derivative of the square root finite.
          strainprod = two*strainmag2 - div2
          if (strainprod .lt. xminn**2) then
            max1 = xminn**2
          else
            max1 = strainprod
          end if
          ss = sqrt(max1)
! laminar kinematic viscosity, inverse wall distance
! squared, chi and fv1.
          nu = rlv(i, j, k)/w(i, j, k, irho)
          dist2inv = one/d2wall(i, j, k)**2
          chi = w(i, j, k, itu1)/nu
          chi2 = chi*chi
          chi3 = chi*chi2
          fv1 = chi3/(chi3+cv13)
! nufv = nu + nutilde*fv1, such that
! stilde * nutilde = ss * nufv.
          nufv = nu + w(i, j, k, itu1)*fv1
          if (nufv .lt. xminn*nu) then
            nufv = xminn*nu
          else
            nufv = nufv
          end if
! r = tanh(nutilde / (stilde kappa^2 d^2)) / tanh(1)
!   = tanh(nutilde^2 / (ss nufv kappa^2 d^2)) / tanh(1).
! no cut-off is needed since r <= 1/tanh(1).
          xx = w(i, j, k, itu1)**2*kar2inv*dist2inv/(ss*nufv)
          tanhx = tanh(xx)
          rr = tanhx*tanhoneinv
          gg = rr + rsacw2*(rr**6-rr)
          gg6 = gg**6
          termfw = ((one+cw36)/(gg6+cw36))**sixth
          fwsa = gg*termfw
! production cb1*stilde*nutilde and destruction.
          if (approxsa) then
            prod = zero
          else
            prod = rsacb1*ss*nufv
          end if
          dest = rsacw1*fwsa*dist2inv*w(i, j, k, itu1)**2
          scratch(i, j, k, idvt) = prod - dest
        end do
      end do
    end do
  end subroutine saedwardssource

!  differentiation of sacompressibilitysource in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: *scratch
!   with respect to varying inputs: *p *w *scratch *vol *si *sj
!                *sk
!   rw status of diff variables: *p:in *w:in *scratch:in-out *vol:in
!                *si:in *sj:in *sk:in
!   plus diff mem management of: p:in w:in scratch:in vol:in si:in
!                sj:in sk:in
  subroutine sacompressibilitysource_d()
!
!  compressibility correction of spalart (aiaa 2000-2306).
!  the term -c5 nutilde^2/a^2 (du_i/dx_j)(du_i/dx_j) is added to
!  the source term stored in scratch(:,:,:,idvt) by sasource or
!  saedwardssource, and its (positive) contribution to
!  -dsource/dnutilde is added to qq.
    use blockpointers
    use constants
    use inputphysics, only : sac5
    implicit none
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: uuxd, uuyd, uuzd, vvxd, vvyd, vvzd, wwxd, &
&   wwyd, wwzd
    real(kind=realtype) :: fact, gradu2, a2inv, compcoef
    real(kind=realtype) :: factd, gradu2d, a2invd, compcoefd
    real(kind=realtype) :: temp
    real(kind=realtype) :: temp0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: temp2
    real(kind=realtype) :: temp3
    real(kind=realtype) :: temp4
    real(kind=realtype) :: temp5
    real(kind=realtype) :: temp6
    real(kind=realtype) :: temp7
    real(kind=realtype) :: temp8
    real(kind=realtype) :: temp9
    real(kind=realtype) :: temp10
    do k=2,kl
      do j=2,jl
        do i=2,il
! velocity gradients in the cell center, scaled by
! 2*vol. see sasource in sa.f90.
          temp = si(i, j, k, 1)
          temp0 = w(i+1, j, k, ivx)
          temp1 = si(i-1, j, k, 1)
          temp2 = w(i-1, j, k, ivx)
          temp3 = sj(i, j, k, 1)
          temp4 = w(i, j+1, k, ivx)
          temp5 = sk(i, j, k, 1)
          temp6 = w(i, j, k+1, ivx)
          temp7 = sj(i, j-1, k, 1)
          temp8 = w(i, j-1, k, ivx)
          temp9 = sk(i, j, k-1, 1)
          temp10 = w(i, j, k-1, ivx)
          uuxd = temp*wd(i+1, j, k, ivx) + temp0*sid(i, j, k, 1) - temp1&
&           *wd(i-1, j, k, ivx) - temp2*sid(i-1, j, k, 1) + temp3*wd(i, &
&           j+1, k, ivx) + temp4*sjd(i, j, k, 1) + temp5*wd(i, j, k+1, &
&           ivx) + temp6*skd(i, j, k, 1) - temp7*wd(i, j-1, k, ivx) - &
&           temp8*sjd(i, j-1, k, 1) - temp9*wd(i, j, k-1, ivx) - temp10*&
&           skd(i, j, k-1, 1)
          uux = temp0*temp - temp2*temp1 + temp4*temp3 + temp6*temp5 - &
&           temp8*temp7 - temp10*temp9
          temp10 = si(i, j, k, 2)
          temp9 = w(i+1, j, k, ivx)
          temp8 = si(i-1, j, k, 2)
          temp7 = w(i-1, j, k, ivx)
          temp6 = sj(i, j, k, 2)
          temp5 = w(i, j+1, k, ivx)
          temp4 = sk(i, j, k, 2)
          temp3 = w(i, j, k+1, ivx)
          temp2 = sj(i, j-1, k, 2)
          temp1 = w(i, j-1, k, ivx)
          temp0 = sk(i, j, k-1, 2)
          temp = w(i, j, k-1, ivx)
          uuyd = temp10*wd(i+1, j, k, ivx) + temp9*sid(i, j, k, 2) - &
&           temp8*wd(i-1, j, k, ivx) - temp7*sid(i-1, j, k, 2) + temp6*&
&           wd(i, j+1, k, ivx) + temp5*sjd(i, j, k, 2) + temp4*wd(i, j, &
&           k+1, ivx) + temp3*skd(i, j, k, 2) - temp2*wd(i, j-1, k, ivx)&
&           - temp1*sjd(i, j-1, k, 2) - temp0*wd(i, j, k-1, ivx) - temp*&
&           skd(i, j, k-1, 2)
          uuy = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 3)
          temp9 = w(i+1, j, k, ivx)
          temp8 = si(i-1, j, k, 3)
          temp7 = w(i-1, j, k, ivx)
          temp6 = sj(i, j, k, 3)
          temp5 = w(i, j+1, k, ivx)
          temp4 = sk(i, j, k, 3)
          temp3 = w(i, j, k+1, ivx)
          temp2 = sj(i, j-1, k, 3)
          temp1 = w(i, j-1, k, ivx)
          temp0 = sk(i, j, k-1, 3)
          temp = w(i, j, k-1, ivx)
          uuzd = temp10*wd(i+1, j, k, ivx) + temp9*sid(i, j, k, 3) - &
&           temp8*wd(i-1, j, k, ivx) - temp7*sid(i-1, j, k, 3) + temp6*&
&           wd(i, j+1, k, ivx) + temp5*sjd(i, j, k, 3) + temp4*wd(i, j, &
&           k+1, ivx) + temp3*skd(i, j, k, 3) - temp2*wd(i, j-1, k, ivx)&
&           - temp1*sjd(i, j-1, k, 3) - temp0*wd(i, j, k-1, ivx) - temp*&
&           skd(i, j, k-1, 3)
          uuz = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 1)
          temp9 = w(i+1, j, k, ivy)
          temp8 = si(i-1, j, k, 1)
          temp7 = w(i-1, j, k, ivy)
          temp6 = sj(i, j, k, 1)
          temp5 = w(i, j+1, k, ivy)
          temp4 = sk(i, j, k, 1)
          temp3 = w(i, j, k+1, ivy)
          temp2 = sj(i, j-1, k, 1)
          temp1 = w(i, j-1, k, ivy)
          temp0 = sk(i, j, k-1, 1)
          temp = w(i, j, k-1, ivy)
          vvxd = temp10*wd(i+1, j, k, ivy) + temp9*sid(i, j, k, 1) - &
&           temp8*wd(i-1, j, k, ivy) - temp7*sid(i-1, j, k, 1) + temp6*&
&           wd(i, j+1, k, ivy) + temp5*sjd(i, j, k, 1) + temp4*wd(i, j, &
&           k+1, ivy) + temp3*skd(i, j, k, 1) - temp2*wd(i, j-1, k, ivy)&
&           - temp1*sjd(i, j-1, k, 1) - temp0*wd(i, j, k-1, ivy) - temp*&
&           skd(i, j, k-1, 1)
          vvx = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 2)
          temp9 = w(i+1, j, k, ivy)
          temp8 = si(i-1, j, k, 2)
          temp7 = w(i-1, j, k, ivy)
          temp6 = sj(i, j, k, 2)
          temp5 = w(i, j+1, k, ivy)
          temp4 = sk(i, j, k, 2)
          temp3 = w(i, j, k+1, ivy)
          temp2 = sj(i, j-1, k, 2)
          temp1 = w(i, j-1, k, ivy)
          temp0 = sk(i, j, k-1, 2)
          temp = w(i, j, k-1, ivy)
          vvyd = temp10*wd(i+1, j, k, ivy) + temp9*sid(i, j, k, 2) - &
&           temp8*wd(i-1, j, k, ivy) - temp7*sid(i-1, j, k, 2) + temp6*&
&           wd(i, j+1, k, ivy) + temp5*sjd(i, j, k, 2) + temp4*wd(i, j, &
&           k+1, ivy) + temp3*skd(i, j, k, 2) - temp2*wd(i, j-1, k, ivy)&
&           - temp1*sjd(i, j-1, k, 2) - temp0*wd(i, j, k-1, ivy) - temp*&
&           skd(i, j, k-1, 2)
          vvy = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 3)
          temp9 = w(i+1, j, k, ivy)
          temp8 = si(i-1, j, k, 3)
          temp7 = w(i-1, j, k, ivy)
          temp6 = sj(i, j, k, 3)
          temp5 = w(i, j+1, k, ivy)
          temp4 = sk(i, j, k, 3)
          temp3 = w(i, j, k+1, ivy)
          temp2 = sj(i, j-1, k, 3)
          temp1 = w(i, j-1, k, ivy)
          temp0 = sk(i, j, k-1, 3)
          temp = w(i, j, k-1, ivy)
          vvzd = temp10*wd(i+1, j, k, ivy) + temp9*sid(i, j, k, 3) - &
&           temp8*wd(i-1, j, k, ivy) - temp7*sid(i-1, j, k, 3) + temp6*&
&           wd(i, j+1, k, ivy) + temp5*sjd(i, j, k, 3) + temp4*wd(i, j, &
&           k+1, ivy) + temp3*skd(i, j, k, 3) - temp2*wd(i, j-1, k, ivy)&
&           - temp1*sjd(i, j-1, k, 3) - temp0*wd(i, j, k-1, ivy) - temp*&
&           skd(i, j, k-1, 3)
          vvz = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 1)
          temp9 = w(i+1, j, k, ivz)
          temp8 = si(i-1, j, k, 1)
          temp7 = w(i-1, j, k, ivz)
          temp6 = sj(i, j, k, 1)
          temp5 = w(i, j+1, k, ivz)
          temp4 = sk(i, j, k, 1)
          temp3 = w(i, j, k+1, ivz)
          temp2 = sj(i, j-1, k, 1)
          temp1 = w(i, j-1, k, ivz)
          temp0 = sk(i, j, k-1, 1)
          temp = w(i, j, k-1, ivz)
          wwxd = temp10*wd(i+1, j, k, ivz) + temp9*sid(i, j, k, 1) - &
&           temp8*wd(i-1, j, k, ivz) - temp7*sid(i-1, j, k, 1) + temp6*&
&           wd(i, j+1, k, ivz) + temp5*sjd(i, j, k, 1) + temp4*wd(i, j, &
&           k+1, ivz) + temp3*skd(i, j, k, 1) - temp2*wd(i, j-1, k, ivz)&
&           - temp1*sjd(i, j-1, k, 1) - temp0*wd(i, j, k-1, ivz) - temp*&
&           skd(i, j, k-1, 1)
          wwx = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 2)
          temp9 = w(i+1, j, k, ivz)
          temp8 = si(i-1, j, k, 2)
          temp7 = w(i-1, j, k, ivz)
          temp6 = sj(i, j, k, 2)
          temp5 = w(i, j+1, k, ivz)
          temp4 = sk(i, j, k, 2)
          temp3 = w(i, j, k+1, ivz)
          temp2 = sj(i, j-1, k, 2)
          temp1 = w(i, j-1, k, ivz)
          temp0 = sk(i, j, k-1, 2)
          temp = w(i, j, k-1, ivz)
          wwyd = temp10*wd(i+1, j, k, ivz) + temp9*sid(i, j, k, 2) - &
&           temp8*wd(i-1, j, k, ivz) - temp7*sid(i-1, j, k, 2) + temp6*&
&           wd(i, j+1, k, ivz) + temp5*sjd(i, j, k, 2) + temp4*wd(i, j, &
&           k+1, ivz) + temp3*skd(i, j, k, 2) - temp2*wd(i, j-1, k, ivz)&
&           - temp1*sjd(i, j-1, k, 2) - temp0*wd(i, j, k-1, ivz) - temp*&
&           skd(i, j, k-1, 2)
          wwy = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
          temp10 = si(i, j, k, 3)
          temp9 = w(i+1, j, k, ivz)
          temp8 = si(i-1, j, k, 3)
          temp7 = w(i-1, j, k, ivz)
          temp6 = sj(i, j, k, 3)
          temp5 = w(i, j+1, k, ivz)
          temp4 = sk(i, j, k, 3)
          temp3 = w(i, j, k+1, ivz)
          temp2 = sj(i, j-1, k, 3)
          temp1 = w(i, j-1, k, ivz)
          temp0 = sk(i, j, k-1, 3)
          temp = w(i, j, k-1, ivz)
          wwzd = temp10*wd(i+1, j, k, ivz) + temp9*sid(i, j, k, 3) - &
&           temp8*wd(i-1, j, k, ivz) - temp7*sid(i-1, j, k, 3) + temp6*&
&           wd(i, j+1, k, ivz) + temp5*sjd(i, j, k, 3) + temp4*wd(i, j, &
&           k+1, ivz) + temp3*skd(i, j, k, 3) - temp2*wd(i, j-1, k, ivz)&
&           - temp1*sjd(i, j-1, k, 3) - temp0*wd(i, j, k-1, ivz) - temp*&
&           skd(i, j, k-1, 3)
          wwz = temp9*temp10 - temp7*temp8 + temp5*temp6 + temp3*temp4 -&
&           temp1*temp2 - temp*temp0
! (du_i/dx_j)(du_i/dx_j); the gradients above are
! scaled by 2*vol.
          temp10 = half/vol(i, j, k)
          factd = -(temp10*vold(i, j, k)/vol(i, j, k))
          fact = temp10
          temp10 = uux*uux + uuy*uuy + uuz*uuz + vvx*vvx + vvy*vvy + vvz&
&           *vvz + wwx*wwx + wwy*wwy + wwz*wwz
          gradu2d = temp10*2*fact*factd + fact**2*(2*uux*uuxd+2*uuy*uuyd&
&           +2*uuz*uuzd+2*vvx*vvxd+2*vvy*vvyd+2*vvz*vvzd+2*wwx*wwxd+2*&
&           wwy*wwyd+2*wwz*wwzd)
          gradu2 = fact*fact*temp10
! inverse of the local speed of sound squared.
          temp10 = gamma(i, j, k)*p(i, j, k)
          temp9 = w(i, j, k, irho)/temp10
          a2invd = (wd(i, j, k, irho)-temp9*gamma(i, j, k)*pd(i, j, k))/&
&           temp10
          a2inv = temp9
          compcoefd = sac5*(gradu2*a2invd+a2inv*gradu2d)
          compcoef = sac5*a2inv*gradu2
          temp10 = w(i, j, k, itu1)
          scratchd(i, j, k, idvt) = scratchd(i, j, k, idvt) - temp10**2*&
&           compcoefd - compcoef*2*temp10*wd(i, j, k, itu1)
          scratch(i, j, k, idvt) = scratch(i, j, k, idvt) - compcoef*(&
&           temp10*temp10)
        end do
      end do
    end do
  end subroutine sacompressibilitysource_d

  subroutine sacompressibilitysource()
!
!  compressibility correction of spalart (aiaa 2000-2306).
!  the term -c5 nutilde^2/a^2 (du_i/dx_j)(du_i/dx_j) is added to
!  the source term stored in scratch(:,:,:,idvt) by sasource or
!  saedwardssource, and its (positive) contribution to
!  -dsource/dnutilde is added to qq.
    use blockpointers
    use constants
    use inputphysics, only : sac5
    implicit none
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: fact, gradu2, a2inv, compcoef
    do k=2,kl
      do j=2,jl
        do i=2,il
! velocity gradients in the cell center, scaled by
! 2*vol. see sasource in sa.f90.
          uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(&
&           i-1, j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1&
&           , k, ivx)*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1&
&           ) - w(i, j, k-1, ivx)*sk(i, j, k-1, 1)
          uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(&
&           i-1, j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1&
&           , k, ivx)*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2&
&           ) - w(i, j, k-1, ivx)*sk(i, j, k-1, 2)
          uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(&
&           i-1, j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1&
&           , k, ivx)*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3&
&           ) - w(i, j, k-1, ivx)*sk(i, j, k-1, 3)
          vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(&
&           i-1, j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1&
&           , k, ivy)*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1&
&           ) - w(i, j, k-1, ivy)*sk(i, j, k-1, 1)
          vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(&
&           i-1, j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1&
&           , k, ivy)*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2&
&           ) - w(i, j, k-1, ivy)*sk(i, j, k-1, 2)
          vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(&
&           i-1, j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1&
&           , k, ivy)*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3&
&           ) - w(i, j, k-1, ivy)*sk(i, j, k-1, 3)
          wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(&
&           i-1, j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1&
&           , k, ivz)*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1&
&           ) - w(i, j, k-1, ivz)*sk(i, j, k-1, 1)
          wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(&
&           i-1, j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1&
&           , k, ivz)*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2&
&           ) - w(i, j, k-1, ivz)*sk(i, j, k-1, 2)
          wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(&
&           i-1, j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1&
&           , k, ivz)*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3&
&           ) - w(i, j, k-1, ivz)*sk(i, j, k-1, 3)
! (du_i/dx_j)(du_i/dx_j); the gradients above are
! scaled by 2*vol.
          fact = half/vol(i, j, k)
          gradu2 = fact**2*(uux**2+uuy**2+uuz**2+vvx**2+vvy**2+vvz**2+&
&           wwx**2+wwy**2+wwz**2)
! inverse of the local speed of sound squared.
          a2inv = w(i, j, k, irho)/(gamma(i, j, k)*p(i, j, k))
          compcoef = sac5*a2inv*gradu2
          scratch(i, j, k, idvt) = scratch(i, j, k, idvt) - compcoef*w(i&
&           , j, k, itu1)**2
        end do
      end do
    end do
  end subroutine sacompressibilitysource

end module sacorrections_d

