!        generated by tapenade     (inria, ecuador team)
!  tapenade 3.16 (develop) -  2 sep 2026 09:00
!
! this module contains the source terms for two variants of the
! spalart-allmaras turbulence model that are not part of the
! "standard" sa implementation in sa.f90:
!
!   1. the edwards-chandra modification (sa-noft2-edwards), selected with
!      turbulencemodel = "sa-edwards":
!
!        edwards, j. r. and chandra, s., "comparison of eddy
!        viscosity-transport turbulence models for three-dimensional,
!        shock-separated flowfields," aiaa paper 94-2275, 1994,
!        https://doi.org/10.2514/6.1994-2275; also aiaa journal,
!        vol. 34, no. 4, 1996, pp. 756-763, https://doi.org/10.2514/3.13137.
!
!      the model is identical to standard sa except that ft2 is ignored
!      and
!
!        stilde = sqrt(s) * (1/chi + fv1)
!        r      = tanh(nutilde / (stilde kappa^2 d^2)) / tanh(1)
!        s      = (du_i/dx_j + du_j/dx_i) du_i/dx_j - 2/3 (du_k/dx_k)^2
!
!      i.e. the strain rate, not the vorticity, drives production. note
!      that stilde * nutilde = sqrt(s) * (nu + nutilde * fv1), which is how
!      the terms are evaluated here to avoid the 1/chi singularity at walls.
!
!   2. the mixing-layer compressibility correction (sa-comp), selected with
!      usecompressibilitysa = true, which can be combined with either
!      "sa" or "sa-edwards":
!
!        spalart, p. r., "trends in turbulence treatments," aiaa paper
!        2000-2306, 2000, https://doi.org/10.2514/6.2000-2306.
!
!      the following term is added to the right hand side of the
!      (non-conservative) nutilde equation,
!
!        -c5 * nutilde^2 / a^2 * (du_i/dx_j) (du_i/dx_j),   c5 = 3.5,
!
!      where a is the local speed of sound.
!
! the routines follow the conventions of sasource in sa.f90: the source
! is stored in scratch(:,:,:,idvt) and -dsource/dnutilde is stored in qq
! for the ddadi solver. they are differentiated with tapenade (see
! adjoint/makefile_tapenade).
module sacorrections_b
  use constants
  implicit none

contains
!  differentiation of saedwardssource in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *w *rlv *scratch *vol *si *sj
!                *sk
!   with respect to varying inputs: *w *rlv *scratch *vol *d2wall
!                *si *sj *sk
!   rw status of diff variables: *w:incr *rlv:incr *scratch:in-out
!                *vol:incr *d2wall:out *si:incr *sj:incr *sk:incr
!   plus diff mem management of: w:in rlv:in scratch:in vol:in
!                d2wall:in si:in sj:in sk:in
  subroutine saedwardssource_b()
!
!  source terms of the edwards-chandra sa model.
!  determine the source term and its derivative w.r.t. nutilde
!  for all internal cells of the block.
!  remember that the sa field variable nutilde = w(i,j,k,itu1)
    use blockpointers
    use constants
    use paramturb
    use inputdiscretization, only : approxsa
    implicit none
! local parameters
    real(kind=realtype), parameter :: f23=two*third
    real(kind=realtype), parameter :: xminn=1.e-10_realtype
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: cv13, kar2inv, cw36, tanhoneinv
    real(kind=realtype) :: fv1, nufv, ss, nu, dist2inv, chi, chi2, chi3
    real(kind=realtype) :: fv1d, nufvd, ssd, nud, dist2invd, chid, chi2d&
&   , chi3d
    real(kind=realtype) :: xx, tanhx, rr, gg, gg6, termfw, fwsa
    real(kind=realtype) :: xxd, tanhxd, rrd, ggd, gg6d, termfwd, fwsad
    real(kind=realtype) :: prod, dest
    real(kind=realtype) :: prodd, destd
    real(kind=realtype) :: dfv1, dnufv, dxx, drr, dgg, dfw
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: uuxd, uuyd, uuzd, vvxd, vvyd, vvzd, wwxd, &
&   wwyd, wwzd
    real(kind=realtype) :: div2, fact, sxx, syy, szz, sxy, sxz, syz
    real(kind=realtype) :: div2d, factd, sxxd, syyd, szzd, sxyd, sxzd, &
&   syzd
    real(kind=realtype) :: strainmag2, strainprod
    real(kind=realtype) :: strainmag2d, strainprodd
    intrinsic tanh
    intrinsic mod
    intrinsic max
    intrinsic sqrt
    real(kind=realtype) :: max1
    real(kind=realtype) :: max1d
    real(kind=realtype) :: temp
    real(kind=realtype) :: tempd
    real(kind=realtype) :: temp0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: tempd0
    real(kind=realtype) :: tempd1
    integer :: branch
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
    tanhoneinv = one/tanh(one)
    if (associated(d2walld)) d2walld = 0.0_8
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the velocity gradients in the cell center,
! scaled by 2*vol. see sasource in sa.f90.
      uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 1)
      uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 2)
      uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 3)
      vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 1)
      vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 2)
      vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 3)
      wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 1)
      wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 2)
      wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 3)
! strain rate tensor; the factor 1/(4*vol) accounts for
! the 2*vol scaling of the gradients.
      fact = fourth/vol(i, j, k)
      sxx = two*fact*uux
      syy = two*fact*vvy
      szz = two*fact*wwz
      sxy = fact*(uuy+vvx)
      sxz = fact*(uuz+wwx)
      syz = fact*(vvz+wwy)
      div2 = f23*(sxx+syy+szz)**2
      strainmag2 = two*(sxy**2+sxz**2+syz**2) + sxx**2 + syy**2 + szz**2
! s = 2 s_ij s_ij - 2/3 (div u)^2. edwards uses sqrt(s).
! limit it from below (like sst in sa.f90), which also
! keeps the derivative of the square root finite.
      strainprod = two*strainmag2 - div2
      if (strainprod .lt. xminn**2) then
        max1 = xminn**2
        call pushcontrol1b(0)
      else
        max1 = strainprod
        call pushcontrol1b(1)
      end if
      ss = sqrt(max1)
! laminar kinematic viscosity, inverse wall distance
! squared, chi and fv1.
      nu = rlv(i, j, k)/w(i, j, k, irho)
      dist2inv = one/d2wall(i, j, k)**2
      chi = w(i, j, k, itu1)/nu
      chi2 = chi*chi
      chi3 = chi*chi2
      fv1 = chi3/(chi3+cv13)
! nufv = nu + nutilde*fv1, such that
! stilde * nutilde = ss * nufv.
      nufv = nu + w(i, j, k, itu1)*fv1
      if (nufv .lt. xminn*nu) then
        nufv = xminn*nu
        call pushcontrol1b(0)
      else
        nufv = nufv
        call pushcontrol1b(1)
      end if
! r = tanh(nutilde / (stilde kappa^2 d^2)) / tanh(1)
!   = tanh(nutilde^2 / (ss nufv kappa^2 d^2)) / tanh(1).
! no cut-off is needed since r <= 1/tanh(1).
      xx = w(i, j, k, itu1)**2*kar2inv*dist2inv/(ss*nufv)
      tanhx = tanh(xx)
      rr = tanhx*tanhoneinv
      gg = rr + rsacw2*(rr**6-rr)
      gg6 = gg**6
      termfw = ((one+cw36)/(gg6+cw36))**sixth
      fwsa = gg*termfw
! production cb1*stilde*nutilde and destruction.
      if (approxsa) then
        call pushcontrol1b(0)
      else
        call pushcontrol1b(1)
      end if
      prodd = scratchd(i, j, k, idvt)
      destd = -scratchd(i, j, k, idvt)
      scratchd(i, j, k, idvt) = 0.0_8
      temp1 = w(i, j, k, itu1)
      tempd1 = temp1**2*rsacw1*destd
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + 2*temp1*fwsa*dist2inv*&
&       rsacw1*destd
      fwsad = dist2inv*tempd1
      dist2invd = fwsa*tempd1
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        nufvd = 0.0_8
        ssd = 0.0_8
      else
        ssd = nufv*rsacb1*prodd
        nufvd = ss*rsacb1*prodd
      end if
      termfwd = gg*fwsad
      temp1 = (one+cw36)/(cw36+gg6)
      if (temp1 .le. 0.0_8 .and. (sixth .eq. 0.0_8 .or. sixth .ne. int(&
&         sixth))) then
        gg6d = 0.0_8
      else
        gg6d = -(temp1*sixth*temp1**(sixth-1)*termfwd/(cw36+gg6))
      end if
      ggd = termfw*fwsad + 6*gg**5*gg6d
      rrd = (6*rr**5*rsacw2-rsacw2+1.0)*ggd
      tanhxd = tanhoneinv*rrd
      xxd = (1.0-tanh(xx)**2)*tanhxd
      temp = dist2inv/(ss*nufv)
      temp0 = w(i, j, k, itu1)
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + 2*temp0*temp*kar2inv*xxd
      tempd = temp0**2*kar2inv*xxd/(ss*nufv)
      dist2invd = dist2invd + tempd
      tempd0 = -(temp*tempd)
      ssd = ssd + nufv*tempd0
      nufvd = nufvd + ss*tempd0
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        nud = xminn*nufvd
        nufvd = 0.0_8
      else
        nud = 0.0_8
      end if
      fv1d = w(i, j, k, itu1)*nufvd
      tempd = fv1d/(cv13+chi3)
      chi3d = (1.0-chi3/(cv13+chi3))*tempd
      chi2d = chi*chi3d
      chid = chi2*chi3d + 2*chi*chi2d
      nud = nud + nufvd - w(i, j, k, itu1)*chid/nu**2
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + fv1*nufvd + chid/nu
      temp = d2wall(i, j, k)
      d2walld(i, j, k) = d2walld(i, j, k) - 2*one*dist2invd/temp**3
      temp = w(i, j, k, irho)
      rlvd(i, j, k) = rlvd(i, j, k) + nud/temp
      wd(i, j, k, irho) = wd(i, j, k, irho) - rlv(i, j, k)*nud/temp**2
      if (max1 .eq. 0.0_8) then
        max1d = 0.0_8
      else
        max1d = ssd/(2.0*sqrt(max1))
      end if
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        strainprodd = 0.0_8
      else
        strainprodd = max1d
      end if
      strainmag2d = two*strainprodd
      div2d = -strainprodd
      tempd = two*strainmag2d
      sxyd = 2*sxy*tempd
      sxzd = 2*sxz*tempd
      syzd = 2*syz*tempd
      tempd = 2*(sxx+syy+szz)*f23*div2d
      sxxd = 2*sxx*strainmag2d + tempd
      syyd = 2*syy*strainmag2d + tempd
      szzd = 2*szz*strainmag2d + tempd
      factd = (vvz+wwy)*syzd + (uuz+wwx)*sxzd + (uuy+vvx)*sxyd + wwz*two&
&       *szzd + vvy*two*syyd + uux*two*sxxd
      vvzd = fact*syzd
      wwyd = fact*syzd
      uuzd = fact*sxzd
      wwxd = fact*sxzd
      uuyd = fact*sxyd
      vvxd = fact*sxyd
      wwzd = fact*two*szzd
      vvyd = fact*two*syyd
      uuxd = fact*two*sxxd
      vold(i, j, k) = vold(i, j, k) - fourth*factd/vol(i, j, k)**2
      sid(i, j, k, 3) = sid(i, j, k, 3) + w(i+1, j, k, ivz)*wwzd
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - w(i-1, j, k, ivz)*wwzd
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + w(i, j+1, k, ivz)*wwzd
      skd(i, j, k, 3) = skd(i, j, k, 3) + w(i, j, k+1, ivz)*wwzd
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - w(i, j-1, k, ivz)*wwzd
      wd(i, j, k-1, ivz) = wd(i, j, k-1, ivz) - sk(i, j, k-1, 3)*wwzd - &
&       sk(i, j, k-1, 2)*wwyd - sk(i, j, k-1, 1)*wwxd
      wd(i, j-1, k, ivz) = wd(i, j-1, k, ivz) - sj(i, j-1, k, 3)*wwzd - &
&       sj(i, j-1, k, 2)*wwyd - sj(i, j-1, k, 1)*wwxd
      wd(i, j, k+1, ivz) = wd(i, j, k+1, ivz) + sk(i, j, k, 3)*wwzd + sk&
&       (i, j, k, 2)*wwyd + sk(i, j, k, 1)*wwxd
      wd(i, j+1, k, ivz) = wd(i, j+1, k, ivz) + sj(i, j, k, 3)*wwzd + sj&
&       (i, j, k, 2)*wwyd + sj(i, j, k, 1)*wwxd
      wd(i-1, j, k, ivz) = wd(i-1, j, k, ivz) - si(i-1, j, k, 3)*wwzd - &
&       si(i-1, j, k, 2)*wwyd - si(i-1, j, k, 1)*wwxd
      wd(i+1, j, k, ivz) = wd(i+1, j, k, ivz) + si(i, j, k, 3)*wwzd + si&
&       (i, j, k, 2)*wwyd + si(i, j, k, 1)*wwxd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - w(i, j, k-1, ivz)*wwzd
      sid(i, j, k, 2) = sid(i, j, k, 2) + w(i+1, j, k, ivz)*wwyd
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - w(i-1, j, k, ivz)*wwyd
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + w(i, j+1, k, ivz)*wwyd
      skd(i, j, k, 2) = skd(i, j, k, 2) + w(i, j, k+1, ivz)*wwyd
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - w(i, j-1, k, ivz)*wwyd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - w(i, j, k-1, ivz)*wwyd
      sid(i, j, k, 1) = sid(i, j, k, 1) + w(i+1, j, k, ivz)*wwxd
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - w(i-1, j, k, ivz)*wwxd
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + w(i, j+1, k, ivz)*wwxd
      skd(i, j, k, 1) = skd(i, j, k, 1) + w(i, j, k+1, ivz)*wwxd
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - w(i, j-1, k, ivz)*wwxd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - w(i, j, k-1, ivz)*wwxd
      sid(i, j, k, 3) = sid(i, j, k, 3) + w(i+1, j, k, ivy)*vvzd
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - w(i-1, j, k, ivy)*vvzd
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + w(i, j+1, k, ivy)*vvzd
      skd(i, j, k, 3) = skd(i, j, k, 3) + w(i, j, k+1, ivy)*vvzd
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - w(i, j-1, k, ivy)*vvzd
      wd(i, j, k-1, ivy) = wd(i, j, k-1, ivy) - sk(i, j, k-1, 3)*vvzd - &
&       sk(i, j, k-1, 2)*vvyd - sk(i, j, k-1, 1)*vvxd
      wd(i, j-1, k, ivy) = wd(i, j-1, k, ivy) - sj(i, j-1, k, 3)*vvzd - &
&       sj(i, j-1, k, 2)*vvyd - sj(i, j-1, k, 1)*vvxd
      wd(i, j, k+1, ivy) = wd(i, j, k+1, ivy) + sk(i, j, k, 3)*vvzd + sk&
&       (i, j, k, 2)*vvyd + sk(i, j, k, 1)*vvxd
      wd(i, j+1, k, ivy) = wd(i, j+1, k, ivy) + sj(i, j, k, 3)*vvzd + sj&
&       (i, j, k, 2)*vvyd + sj(i, j, k, 1)*vvxd
      wd(i-1, j, k, ivy) = wd(i-1, j, k, ivy) - si(i-1, j, k, 3)*vvzd - &
&       si(i-1, j, k, 2)*vvyd - si(i-1, j, k, 1)*vvxd
      wd(i+1, j, k, ivy) = wd(i+1, j, k, ivy) + si(i, j, k, 3)*vvzd + si&
&       (i, j, k, 2)*vvyd + si(i, j, k, 1)*vvxd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - w(i, j, k-1, ivy)*vvzd
      sid(i, j, k, 2) = sid(i, j, k, 2) + w(i+1, j, k, ivy)*vvyd
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - w(i-1, j, k, ivy)*vvyd
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + w(i, j+1, k, ivy)*vvyd
      skd(i, j, k, 2) = skd(i, j, k, 2) + w(i, j, k+1, ivy)*vvyd
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - w(i, j-1, k, ivy)*vvyd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - w(i, j, k-1, ivy)*vvyd
      sid(i, j, k, 1) = sid(i, j, k, 1) + w(i+1, j, k, ivy)*vvxd
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - w(i-1, j, k, ivy)*vvxd
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + w(i, j+1, k, ivy)*vvxd
      skd(i, j, k, 1) = skd(i, j, k, 1) + w(i, j, k+1, ivy)*vvxd
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - w(i, j-1, k, ivy)*vvxd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - w(i, j, k-1, ivy)*vvxd
      sid(i, j, k, 3) = sid(i, j, k, 3) + w(i+1, j, k, ivx)*uuzd
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - w(i-1, j, k, ivx)*uuzd
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + w(i, j+1, k, ivx)*uuzd
      skd(i, j, k, 3) = skd(i, j, k, 3) + w(i, j, k+1, ivx)*uuzd
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - w(i, j-1, k, ivx)*uuzd
      wd(i, j, k-1, ivx) = wd(i, j, k-1, ivx) - sk(i, j, k-1, 3)*uuzd - &
&       sk(i, j, k-1, 2)*uuyd - sk(i, j, k-1, 1)*uuxd
      wd(i, j-1, k, ivx) = wd(i, j-1, k, ivx) - sj(i, j-1, k, 3)*uuzd - &
&       sj(i, j-1, k, 2)*uuyd - sj(i, j-1, k, 1)*uuxd
      wd(i, j, k+1, ivx) = wd(i, j, k+1, ivx) + sk(i, j, k, 3)*uuzd + sk&
&       (i, j, k, 2)*uuyd + sk(i, j, k, 1)*uuxd
      wd(i, j+1, k, ivx) = wd(i, j+1, k, ivx) + sj(i, j, k, 3)*uuzd + sj&
&       (i, j, k, 2)*uuyd + sj(i, j, k, 1)*uuxd
      wd(i-1, j, k, ivx) = wd(i-1, j, k, ivx) - si(i-1, j, k, 3)*uuzd - &
&       si(i-1, j, k, 2)*uuyd - si(i-1, j, k, 1)*uuxd
      wd(i+1, j, k, ivx) = wd(i+1, j, k, ivx) + si(i, j, k, 3)*uuzd + si&
&       (i, j, k, 2)*uuyd + si(i, j, k, 1)*uuxd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - w(i, j, k-1, ivx)*uuzd
      sid(i, j, k, 2) = sid(i, j, k, 2) + w(i+1, j, k, ivx)*uuyd
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - w(i-1, j, k, ivx)*uuyd
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + w(i, j+1, k, ivx)*uuyd
      skd(i, j, k, 2) = skd(i, j, k, 2) + w(i, j, k+1, ivx)*uuyd
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - w(i, j-1, k, ivx)*uuyd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - w(i, j, k-1, ivx)*uuyd
      sid(i, j, k, 1) = sid(i, j, k, 1) + w(i+1, j, k, ivx)*uuxd
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - w(i-1, j, k, ivx)*uuxd
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + w(i, j+1, k, ivx)*uuxd
      skd(i, j, k, 1) = skd(i, j, k, 1) + w(i, j, k+1, ivx)*uuxd
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - w(i, j-1, k, ivx)*uuxd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - w(i, j, k-1, ivx)*uuxd
    end do
  end subroutine saedwardssource_b

  subroutine saedwardssource()
!
!  source terms of the edwards-chandra sa model.
!  determine the source term and its derivative w.r.t. nutilde
!  for all internal cells of the block.
!  remember that the sa field variable nutilde = w(i,j,k,itu1)
    use blockpointers
    use constants
    use paramturb
    use inputdiscretization, only : approxsa
    implicit none
! local parameters
    real(kind=realtype), parameter :: f23=two*third
    real(kind=realtype), parameter :: xminn=1.e-10_realtype
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: cv13, kar2inv, cw36, tanhoneinv
    real(kind=realtype) :: fv1, nufv, ss, nu, dist2inv, chi, chi2, chi3
    real(kind=realtype) :: xx, tanhx, rr, gg, gg6, termfw, fwsa
    real(kind=realtype) :: prod, dest
    real(kind=realtype) :: dfv1, dnufv, dxx, drr, dgg, dfw
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: div2, fact, sxx, syy, szz, sxy, sxz, syz
    real(kind=realtype) :: strainmag2, strainprod
    intrinsic tanh
    intrinsic mod
    intrinsic max
    intrinsic sqrt
    real(kind=realtype) :: max1
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
    tanhoneinv = one/tanh(one)
!$ad ii-loop
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the velocity gradients in the cell center,
! scaled by 2*vol. see sasource in sa.f90.
      uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 1)
      uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 2)
      uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 3)
      vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 1)
      vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 2)
      vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 3)
      wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 1)
      wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 2)
      wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 3)
! strain rate tensor; the factor 1/(4*vol) accounts for
! the 2*vol scaling of the gradients.
      fact = fourth/vol(i, j, k)
      sxx = two*fact*uux
      syy = two*fact*vvy
      szz = two*fact*wwz
      sxy = fact*(uuy+vvx)
      sxz = fact*(uuz+wwx)
      syz = fact*(vvz+wwy)
      div2 = f23*(sxx+syy+szz)**2
      strainmag2 = two*(sxy**2+sxz**2+syz**2) + sxx**2 + syy**2 + szz**2
! s = 2 s_ij s_ij - 2/3 (div u)^2. edwards uses sqrt(s).
! limit it from below (like sst in sa.f90), which also
! keeps the derivative of the square root finite.
      strainprod = two*strainmag2 - div2
      if (strainprod .lt. xminn**2) then
        max1 = xminn**2
      else
        max1 = strainprod
      end if
      ss = sqrt(max1)
! laminar kinematic viscosity, inverse wall distance
! squared, chi and fv1.
      nu = rlv(i, j, k)/w(i, j, k, irho)
      dist2inv = one/d2wall(i, j, k)**2
      chi = w(i, j, k, itu1)/nu
      chi2 = chi*chi
      chi3 = chi*chi2
      fv1 = chi3/(chi3+cv13)
! nufv = nu + nutilde*fv1, such that
! stilde * nutilde = ss * nufv.
      nufv = nu + w(i, j, k, itu1)*fv1
      if (nufv .lt. xminn*nu) then
        nufv = xminn*nu
      else
        nufv = nufv
      end if
! r = tanh(nutilde / (stilde kappa^2 d^2)) / tanh(1)
!   = tanh(nutilde^2 / (ss nufv kappa^2 d^2)) / tanh(1).
! no cut-off is needed since r <= 1/tanh(1).
      xx = w(i, j, k, itu1)**2*kar2inv*dist2inv/(ss*nufv)
      tanhx = tanh(xx)
      rr = tanhx*tanhoneinv
      gg = rr + rsacw2*(rr**6-rr)
      gg6 = gg**6
      termfw = ((one+cw36)/(gg6+cw36))**sixth
      fwsa = gg*termfw
! production cb1*stilde*nutilde and destruction.
      if (approxsa) then
        prod = zero
      else
        prod = rsacb1*ss*nufv
      end if
      dest = rsacw1*fwsa*dist2inv*w(i, j, k, itu1)**2
      scratch(i, j, k, idvt) = prod - dest
    end do
  end subroutine saedwardssource

!  differentiation of sacompressibilitysource in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *p *w *scratch *vol *si *sj
!                *sk
!   with respect to varying inputs: *p *w *scratch *vol *si *sj
!                *sk
!   rw status of diff variables: *p:incr *w:incr *scratch:in-out
!                *vol:incr *si:incr *sj:incr *sk:incr
!   plus diff mem management of: p:in w:in scratch:in vol:in si:in
!                sj:in sk:in
  subroutine sacompressibilitysource_b()
!
!  compressibility correction of spalart (aiaa 2000-2306).
!  the term -c5 nutilde^2/a^2 (du_i/dx_j)(du_i/dx_j) is added to
!  the source term stored in scratch(:,:,:,idvt) by sasource or
!  saedwardssource, and its (positive) contribution to
!  -dsource/dnutilde is added to qq.
    use blockpointers
    use constants
    use inputphysics, only : sac5
    implicit none
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: uuxd, uuyd, uuzd, vvxd, vvyd, vvzd, wwxd, &
&   wwyd, wwzd
    real(kind=realtype) :: fact, gradu2, a2inv, compcoef
    real(kind=realtype) :: factd, gradu2d, a2invd, compcoefd
    intrinsic mod
    real(kind=realtype) :: temp
    real(kind=realtype) :: tempd
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! velocity gradients in the cell center, scaled by
! 2*vol. see sasource in sa.f90.
      uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 1)
      uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 2)
      uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 3)
      vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 1)
      vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 2)
      vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 3)
      wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 1)
      wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 2)
      wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 3)
! (du_i/dx_j)(du_i/dx_j); the gradients above are
! scaled by 2*vol.
      fact = half/vol(i, j, k)
      gradu2 = fact**2*(uux**2+uuy**2+uuz**2+vvx**2+vvy**2+vvz**2+wwx**2&
&       +wwy**2+wwz**2)
! inverse of the local speed of sound squared.
      a2inv = w(i, j, k, irho)/(gamma(i, j, k)*p(i, j, k))
      compcoef = sac5*a2inv*gradu2
      temp = w(i, j, k, itu1)
      compcoefd = -(temp**2*scratchd(i, j, k, idvt))
      wd(i, j, k, itu1) = wd(i, j, k, itu1) - 2*temp*compcoef*scratchd(i&
&       , j, k, idvt)
      a2invd = gradu2*sac5*compcoefd
      gradu2d = a2inv*sac5*compcoefd
      temp = gamma(i, j, k)*p(i, j, k)
      wd(i, j, k, irho) = wd(i, j, k, irho) + a2invd/temp
      pd(i, j, k) = pd(i, j, k) - gamma(i, j, k)*w(i, j, k, irho)*a2invd&
&       /temp**2
      factd = 2*fact*(uux**2+uuy**2+uuz**2+vvx**2+vvy**2+vvz**2+wwx**2+&
&       wwy**2+wwz**2)*gradu2d
      tempd = fact**2*gradu2d
      uuxd = 2*uux*tempd
      uuyd = 2*uuy*tempd
      uuzd = 2*uuz*tempd
      vvxd = 2*vvx*tempd
      vvyd = 2*vvy*tempd
      vvzd = 2*vvz*tempd
      wwxd = 2*wwx*tempd
      wwyd = 2*wwy*tempd
      wwzd = 2*wwz*tempd
      vold(i, j, k) = vold(i, j, k) - half*factd/vol(i, j, k)**2
      sid(i, j, k, 3) = sid(i, j, k, 3) + w(i+1, j, k, ivz)*wwzd
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - w(i-1, j, k, ivz)*wwzd
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + w(i, j+1, k, ivz)*wwzd
      skd(i, j, k, 3) = skd(i, j, k, 3) + w(i, j, k+1, ivz)*wwzd
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - w(i, j-1, k, ivz)*wwzd
      wd(i, j, k-1, ivz) = wd(i, j, k-1, ivz) - sk(i, j, k-1, 3)*wwzd - &
&       sk(i, j, k-1, 2)*wwyd - sk(i, j, k-1, 1)*wwxd
      wd(i, j-1, k, ivz) = wd(i, j-1, k, ivz) - sj(i, j-1, k, 3)*wwzd - &
&       sj(i, j-1, k, 2)*wwyd - sj(i, j-1, k, 1)*wwxd
      wd(i, j, k+1, ivz) = wd(i, j, k+1, ivz) + sk(i, j, k, 3)*wwzd + sk&
&       (i, j, k, 2)*wwyd + sk(i, j, k, 1)*wwxd
      wd(i, j+1, k, ivz) = wd(i, j+1, k, ivz) + sj(i, j, k, 3)*wwzd + sj&
&       (i, j, k, 2)*wwyd + sj(i, j, k, 1)*wwxd
      wd(i-1, j, k, ivz) = wd(i-1, j, k, ivz) - si(i-1, j, k, 3)*wwzd - &
&       si(i-1, j, k, 2)*wwyd - si(i-1, j, k, 1)*wwxd
      wd(i+1, j, k, ivz) = wd(i+1, j, k, ivz) + si(i, j, k, 3)*wwzd + si&
&       (i, j, k, 2)*wwyd + si(i, j, k, 1)*wwxd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - w(i, j, k-1, ivz)*wwzd
      sid(i, j, k, 2) = sid(i, j, k, 2) + w(i+1, j, k, ivz)*wwyd
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - w(i-1, j, k, ivz)*wwyd
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + w(i, j+1, k, ivz)*wwyd
      skd(i, j, k, 2) = skd(i, j, k, 2) + w(i, j, k+1, ivz)*wwyd
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - w(i, j-1, k, ivz)*wwyd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - w(i, j, k-1, ivz)*wwyd
      sid(i, j, k, 1) = sid(i, j, k, 1) + w(i+1, j, k, ivz)*wwxd
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - w(i-1, j, k, ivz)*wwxd
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + w(i, j+1, k, ivz)*wwxd
      skd(i, j, k, 1) = skd(i, j, k, 1) + w(i, j, k+1, ivz)*wwxd
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - w(i, j-1, k, ivz)*wwxd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - w(i, j, k-1, ivz)*wwxd
      sid(i, j, k, 3) = sid(i, j, k, 3) + w(i+1, j, k, ivy)*vvzd
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - w(i-1, j, k, ivy)*vvzd
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + w(i, j+1, k, ivy)*vvzd
      skd(i, j, k, 3) = skd(i, j, k, 3) + w(i, j, k+1, ivy)*vvzd
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - w(i, j-1, k, ivy)*vvzd
      wd(i, j, k-1, ivy) = wd(i, j, k-1, ivy) - sk(i, j, k-1, 3)*vvzd - &
&       sk(i, j, k-1, 2)*vvyd - sk(i, j, k-1, 1)*vvxd
      wd(i, j-1, k, ivy) = wd(i, j-1, k, ivy) - sj(i, j-1, k, 3)*vvzd - &
&       sj(i, j-1, k, 2)*vvyd - sj(i, j-1, k, 1)*vvxd
      wd(i, j, k+1, ivy) = wd(i, j, k+1, ivy) + sk(i, j, k, 3)*vvzd + sk&
&       (i, j, k, 2)*vvyd + sk(i, j, k, 1)*vvxd
      wd(i, j+1, k, ivy) = wd(i, j+1, k, ivy) + sj(i, j, k, 3)*vvzd + sj&
&       (i, j, k, 2)*vvyd + sj(i, j, k, 1)*vvxd
      wd(i-1, j, k, ivy) = wd(i-1, j, k, ivy) - si(i-1, j, k, 3)*vvzd - &
&       si(i-1, j, k, 2)*vvyd - si(i-1, j, k, 1)*vvxd
      wd(i+1, j, k, ivy) = wd(i+1, j, k, ivy) + si(i, j, k, 3)*vvzd + si&
&       (i, j, k, 2)*vvyd + si(i, j, k, 1)*vvxd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - w(i, j, k-1, ivy)*vvzd
      sid(i, j, k, 2) = sid(i, j, k, 2) + w(i+1, j, k, ivy)*vvyd
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - w(i-1, j, k, ivy)*vvyd
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + w(i, j+1, k, ivy)*vvyd
      skd(i, j, k, 2) = skd(i, j, k, 2) + w(i, j, k+1, ivy)*vvyd
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - w(i, j-1, k, ivy)*vvyd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - w(i, j, k-1, ivy)*vvyd
      sid(i, j, k, 1) = sid(i, j, k, 1) + w(i+1, j, k, ivy)*vvxd
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - w(i-1, j, k, ivy)*vvxd
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + w(i, j+1, k, ivy)*vvxd
      skd(i, j, k, 1) = skd(i, j, k, 1) + w(i, j, k+1, ivy)*vvxd
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - w(i, j-1, k, ivy)*vvxd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - w(i, j, k-1, ivy)*vvxd
      sid(i, j, k, 3) = sid(i, j, k, 3) + w(i+1, j, k, ivx)*uuzd
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - w(i-1, j, k, ivx)*uuzd
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + w(i, j+1, k, ivx)*uuzd
      skd(i, j, k, 3) = skd(i, j, k, 3) + w(i, j, k+1, ivx)*uuzd
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - w(i, j-1, k, ivx)*uuzd
      wd(i, j, k-1, ivx) = wd(i, j, k-1, ivx) - sk(i, j, k-1, 3)*uuzd - &
&       sk(i, j, k-1, 2)*uuyd - sk(i, j, k-1, 1)*uuxd
      wd(i, j-1, k, ivx) = wd(i, j-1, k, ivx) - sj(i, j-1, k, 3)*uuzd - &
&       sj(i, j-1, k, 2)*uuyd - sj(i, j-1, k, 1)*uuxd
      wd(i, j, k+1, ivx) = wd(i, j, k+1, ivx) + sk(i, j, k, 3)*uuzd + sk&
&       (i, j, k, 2)*uuyd + sk(i, j, k, 1)*uuxd
      wd(i, j+1, k, ivx) = wd(i, j+1, k, ivx) + sj(i, j, k, 3)*uuzd + sj&
&       (i, j, k, 2)*uuyd + sj(i, j, k, 1)*uuxd
      wd(i-1, j, k, ivx) = wd(i-1, j, k, ivx) - si(i-1, j, k, 3)*uuzd - &
&       si(i-1, j, k, 2)*uuyd - si(i-1, j, k, 1)*uuxd
      wd(i+1, j, k, ivx) = wd(i+1, j, k, ivx) + si(i, j, k, 3)*uuzd + si&
&       (i, j, k, 2)*uuyd + si(i, j, k, 1)*uuxd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - w(i, j, k-1, ivx)*uuzd
      sid(i, j, k, 2) = sid(i, j, k, 2) + w(i+1, j, k, ivx)*uuyd
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - w(i-1, j, k, ivx)*uuyd
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + w(i, j+1, k, ivx)*uuyd
      skd(i, j, k, 2) = skd(i, j, k, 2) + w(i, j, k+1, ivx)*uuyd
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - w(i, j-1, k, ivx)*uuyd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - w(i, j, k-1, ivx)*uuyd
      sid(i, j, k, 1) = sid(i, j, k, 1) + w(i+1, j, k, ivx)*uuxd
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - w(i-1, j, k, ivx)*uuxd
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + w(i, j+1, k, ivx)*uuxd
      skd(i, j, k, 1) = skd(i, j, k, 1) + w(i, j, k+1, ivx)*uuxd
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - w(i, j-1, k, ivx)*uuxd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - w(i, j, k-1, ivx)*uuxd
    end do
  end subroutine sacompressibilitysource_b

  subroutine sacompressibilitysource()
!
!  compressibility correction of spalart (aiaa 2000-2306).
!  the term -c5 nutilde^2/a^2 (du_i/dx_j)(du_i/dx_j) is added to
!  the source term stored in scratch(:,:,:,idvt) by sasource or
!  saedwardssource, and its (positive) contribution to
!  -dsource/dnutilde is added to qq.
    use blockpointers
    use constants
    use inputphysics, only : sac5
    implicit none
! local variables.
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: fact, gradu2, a2inv, compcoef
    intrinsic mod
!$ad ii-loop
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! velocity gradients in the cell center, scaled by
! 2*vol. see sasource in sa.f90.
      uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 1)
      uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 2)
      uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1, k, ivx&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivx)*sk(i, j, k-1, 3)
      vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 1)
      vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 2)
      vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1, k, ivy&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivy)*sk(i, j, k-1, 3)
      wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 1)
      wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 2)
      wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(i-1&
&       , j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1, k, ivz&
&       )*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3) - w(i, j, &
&       k-1, ivz)*sk(i, j, k-1, 3)
! (du_i/dx_j)(du_i/dx_j); the gradients above are
! scaled by 2*vol.
      fact = half/vol(i, j, k)
      gradu2 = fact**2*(uux**2+uuy**2+uuz**2+vvx**2+vvy**2+vvz**2+wwx**2&
&       +wwy**2+wwz**2)
! inverse of the local speed of sound squared.
      a2inv = w(i, j, k, irho)/(gamma(i, j, k)*p(i, j, k))
      compcoef = sac5*a2inv*gradu2
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) - compcoef*w(i, j&
&       , k, itu1)**2
    end do
  end subroutine sacompressibilitysource

end module sacorrections_b

